# Generated by Django 4.1.5 on 2023-01-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
