# Generated by Django 4.1.5 on 2023-01-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
